# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networktests.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='networktests.proto',
  package='heron.proto.testing',
  serialized_pb='\n\x12networktests.proto\x12\x13heron.proto.testing\")\n\x11\x45\x63hoServerRequest\x12\x14\n\x0c\x65\x63ho_request\x18\x01 \x02(\t\"+\n\x12\x45\x63hoServerResponse\x12\x15\n\recho_response\x18\x01 \x02(\tB(\n\x1f\x63om.twitter.heron.proto.testingB\x05Tests')




_ECHOSERVERREQUEST = _descriptor.Descriptor(
  name='EchoServerRequest',
  full_name='heron.proto.testing.EchoServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='echo_request', full_name='heron.proto.testing.EchoServerRequest.echo_request', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=84,
)


_ECHOSERVERRESPONSE = _descriptor.Descriptor(
  name='EchoServerResponse',
  full_name='heron.proto.testing.EchoServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='echo_response', full_name='heron.proto.testing.EchoServerResponse.echo_response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['EchoServerRequest'] = _ECHOSERVERREQUEST
DESCRIPTOR.message_types_by_name['EchoServerResponse'] = _ECHOSERVERRESPONSE

class EchoServerRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOSERVERREQUEST

  # @@protoc_insertion_point(class_scope:heron.proto.testing.EchoServerRequest)

class EchoServerResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOSERVERRESPONSE

  # @@protoc_insertion_point(class_scope:heron.proto.testing.EchoServerResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\037com.twitter.heron.proto.testingB\005Tests')
# @@protoc_insertion_point(module_scope)
