# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: physical_plan.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import topology_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='physical_plan.proto',
  package='heron.proto.system',
  serialized_pb='\n\x13physical_plan.proto\x12\x12heron.proto.system\x1a\x0etopology.proto\"\x7f\n\x05StMgr\x12\n\n\x02id\x18\x01 \x02(\t\x12\x11\n\thost_name\x18\x02 \x02(\t\x12\x11\n\tdata_port\x18\x03 \x02(\x05\x12\x16\n\x0elocal_endpoint\x18\x04 \x02(\t\x12\x0b\n\x03\x63wd\x18\x05 \x01(\t\x12\x0b\n\x03pid\x18\x06 \x01(\x05\x12\x12\n\nshell_port\x18\x07 \x01(\x05\"`\n\x0cInstanceInfo\x12\x0f\n\x07task_id\x18\x01 \x02(\x05\x12\x17\n\x0f\x63omponent_index\x18\x02 \x02(\x05\x12\x16\n\x0e\x63omponent_name\x18\x03 \x02(\t\x12\x0e\n\x06params\x18\x04 \x03(\t\"a\n\x08Instance\x12\x13\n\x0binstance_id\x18\x01 \x02(\t\x12\x10\n\x08stmgr_id\x18\x02 \x02(\t\x12.\n\x04info\x18\x03 \x02(\x0b\x32 .heron.proto.system.InstanceInfo\"\x97\x01\n\x0cPhysicalPlan\x12+\n\x08topology\x18\x01 \x02(\x0b\x32\x19.heron.proto.api.Topology\x12)\n\x06stmgrs\x18\x02 \x03(\x0b\x32\x19.heron.proto.system.StMgr\x12/\n\tinstances\x18\x03 \x03(\x0b\x32\x1c.heron.proto.system.InstanceB/\n\x1e\x63om.twitter.heron.proto.systemB\rPhysicalPlans')




_STMGR = _descriptor.Descriptor(
  name='StMgr',
  full_name='heron.proto.system.StMgr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='heron.proto.system.StMgr.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_name', full_name='heron.proto.system.StMgr.host_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_port', full_name='heron.proto.system.StMgr.data_port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_endpoint', full_name='heron.proto.system.StMgr.local_endpoint', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cwd', full_name='heron.proto.system.StMgr.cwd', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='heron.proto.system.StMgr.pid', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shell_port', full_name='heron.proto.system.StMgr.shell_port', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=186,
)


_INSTANCEINFO = _descriptor.Descriptor(
  name='InstanceInfo',
  full_name='heron.proto.system.InstanceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='heron.proto.system.InstanceInfo.task_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_index', full_name='heron.proto.system.InstanceInfo.component_index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_name', full_name='heron.proto.system.InstanceInfo.component_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='heron.proto.system.InstanceInfo.params', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=284,
)


_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='heron.proto.system.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='heron.proto.system.Instance.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgr_id', full_name='heron.proto.system.Instance.stmgr_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='heron.proto.system.Instance.info', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=286,
  serialized_end=383,
)


_PHYSICALPLAN = _descriptor.Descriptor(
  name='PhysicalPlan',
  full_name='heron.proto.system.PhysicalPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology', full_name='heron.proto.system.PhysicalPlan.topology', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgrs', full_name='heron.proto.system.PhysicalPlan.stmgrs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instances', full_name='heron.proto.system.PhysicalPlan.instances', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=386,
  serialized_end=537,
)

_INSTANCE.fields_by_name['info'].message_type = _INSTANCEINFO
_PHYSICALPLAN.fields_by_name['topology'].message_type = topology_pb2._TOPOLOGY
_PHYSICALPLAN.fields_by_name['stmgrs'].message_type = _STMGR
_PHYSICALPLAN.fields_by_name['instances'].message_type = _INSTANCE
DESCRIPTOR.message_types_by_name['StMgr'] = _STMGR
DESCRIPTOR.message_types_by_name['InstanceInfo'] = _INSTANCEINFO
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['PhysicalPlan'] = _PHYSICALPLAN

class StMgr(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STMGR

  # @@protoc_insertion_point(class_scope:heron.proto.system.StMgr)

class InstanceInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTANCEINFO

  # @@protoc_insertion_point(class_scope:heron.proto.system.InstanceInfo)

class Instance(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTANCE

  # @@protoc_insertion_point(class_scope:heron.proto.system.Instance)

class PhysicalPlan(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHYSICALPLAN

  # @@protoc_insertion_point(class_scope:heron.proto.system.PhysicalPlan)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\036com.twitter.heron.proto.systemB\rPhysicalPlans')
# @@protoc_insertion_point(module_scope)
