# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='heron.proto.system',
  serialized_pb='\n\x0bstats.proto\x12\x12heron.proto.system\"\x0c\n\nStMgrStatsB\'\n\x1e\x63om.twitter.heron.proto.systemB\x05Stats')




_STMGRSTATS = _descriptor.Descriptor(
  name='StMgrStats',
  full_name='heron.proto.system.StMgrStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['StMgrStats'] = _STMGRSTATS

class StMgrStats(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STMGRSTATS

  # @@protoc_insertion_point(class_scope:heron.proto.system.StMgrStats)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\036com.twitter.heron.proto.systemB\005Stats')
# @@protoc_insertion_point(module_scope)
